### ISSUE TITLE
using environment

### ISSUE THREAD

**Issue by BAIYIMING520** [colmsjo/github-issues-export#16]
I try to use this script to download some open source soft engineering, such as vscode, but when i  use npm install to deploy my run enviorment, I get a such error
------------------------------------------------------
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cauthy/Desktop/downloadissues/github-issues-export/node_modules/contextify
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cauthy/.npm/_logs/2020-03-17T10_03_35_498Z-debug.log
------------------------------------------------------------
what should I do could you give me tips?

     my node is v13.8.0
    I use homebrew to get my node environment

**Comment by colmsjo** [comment]
I'd check the node version supported by the library contextify.

**Comment by BAIYIMING520** [comment]
thanks,you are my god! 
I'm doing something urgent job 

github-issues-export@0.1.0 /Users/cauthy/Desktop/downloadissues/github-issues-export
├── jQuery@1.7.4
├── UNMET DEPENDENCY jsdom@~0.6.0
├─┬ optimist@0.4.0
│ └── wordwrap@0.0.3
└── xmlhttprequest@1.5.0
maybe the second lib get some wrong

**Comment by BAIYIMING520** [comment]
您还没有更新吗？
